import Head from 'next/head';
import Hp from '../components/hp';

export default function Home() {
  return (
    <>
      <Head>
        <title>ConNeuNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Hp/>
      </main>
    </>
  )
}
